makefile: ignore errors during clean
KinesisCorporation/Adv360-Pro-ZMK pull request #36
Opened 2022-10-24 04:37 UTC by craftyguy

The file(s) being removed may not exist, but make shouldn't fail because of it:

        $ make clean
        rm ./firmware/*.uf2
        rm: cannot remove './firmware/*.uf2': No such file or directory
        make: *** [Makefile:10: clean] Error 1
        $ echo $?
        2

-f silences any output from rm even though the single dash tells make to ignore the failure, which just creates noise.

2022-10-24 04:37 UTC, craftyguy commented
maybe this is too aggressive, and -f should be removed in case the failure is legitimate (e.g. no write access to the file(s)?), what do y'all think?

2022-10-24 17:16 UTC, allanwind commented
I suggest you remove `-` in `-rm` as you can get that effect by setting `MAKEFLAGS=--silent` in your environment, and seeing the output is the expected behavior.

Perfectly happy with the `-f`.

As we assume we are running in the top-level directory (which is reasonable) remove the `./` prefix.  If you want to be able to run make from any directory then here is how to find it TOP:=$(dir $(lastword $(MAKEFILE_LIST)))`.

Do we need the $(PWD) in the firmware rules?  If not remove those too.

Unrelated... does the .PHONY target with dependencies do anything with those dependencies?  If not I suggest we remove them.  `podman build --tag zmk --file Dockerfile .` on a cached setup takes ~1 second the 2nd time using cached values so I suggest we just eliminate the non-standard setup target and and just do the `docker run` in the firmware rules.  The big win was leaving the container around instead of rebuilding those each time, and standard Makefile.  What about adding a distclean target to remove the containers and images?  I will be adding a install target for my update script.

2022-10-24 17:33 UTC, allanwind requested changes
Update commit message to remove the "the single dash" part.  I had a few other suggestions (above) that I suggest we just squeeze in here.

2022-10-24 18:06 UTC, craftyguy commented
> Do we need the $(PWD) in the firmware rules? If not remove those too.

Seems like it is, else the build fails because it can't find the board (presumably because config wasn't passed into the container?)

<details><summary>output from failed `make`</summary>

```
❯ make
/usr/bin/podman build --tag zmk --file Dockerfile .
STEP 1/8: FROM zmkfirmware/zmk-build-arm:stable
STEP 2/8: WORKDIR /app
--> Using cache bade143b745e858d2f65fd714ab001507307af52e1cdc7254b98fbd209ddecd4
--> bade143b745
STEP 3/8: COPY config/west.yml config/west.yml
--> Using cache be17afca292457eb802114b7aff70a9c4abb97e50ea45b0b7c861e76176cf8f0
--> be17afca292
STEP 4/8: RUN west init -l config
--> Using cache ba65ab0dc1008cb764c663dd42de67b5619590b57b93238a861b9cff181c3613
--> ba65ab0dc10
STEP 5/8: RUN west update
--> Using cache c860839014315c2b3b99c656b0b4c558607cc08497fb275f85946223f904cf0e
--> c8608390143
STEP 6/8: RUN west zephyr-export
--> Using cache 6dd04f480a311216d60bbd41a3e6bc1b4729c0c1e19b6a67563b6642951dbc74
--> 6dd04f480a3
STEP 7/8: COPY bin/build.sh ./
--> Using cache c4f467b0cb48c8b04602642c2a9e2242c617d9971ecee86686f005fbfae7eb32
--> c4f467b0cb4
STEP 8/8: CMD ["./build.sh"]
--> Using cache 12d3fe25915cf88ed90cf0225553e11803181299e80898cf078383ff2d0317bc
COMMIT zmk
--> 12d3fe25915
Successfully tagged localhost/zmk:latest
12d3fe25915cf88ed90cf0225553e11803181299e80898cf078383ff2d0317bc
echo /home/clayton/src/Adv360-Pro-ZMK
/home/clayton/src/Adv360-Pro-ZMK
/usr/bin/podman  run --rm -it --name zmk \
        -v firmware:/app/firmware \
        -v config:/app/config:ro \
        -e TIMESTAMP=20221024175615 \
        zmk
-- west build: generating a build system
Including boilerplate (Zephyr base): /app/zephyr/cmake/app/boilerplate.cmake
-- Application: /app/zmk/app
-- ZMK Config directory: /app/config
CMake Warning at cmake/ZephyrBuildConfig.cmake:199 (message):
  Failed to locate keymap file!
Call Stack (most recent call first):
  /app/zephyr/cmake/app/boilerplate.cmake:113 (find_package)
  /app/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /app/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:15 (find_package)


-- Zephyr version: 3.0.0 (/app/zephyr)
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter
-- Found west (found suitable version "0.12.0", minimum required is "0.7.1")
-- Board: adv360_left
No board named 'adv360_left' found.

Please choose one of the following boards:

arc:
  em_starterkit
<truncated>
CMake Error at /app/zephyr/cmake/app/boilerplate.cmake:388 (message):
  Invalid BOARD; see above.
Call Stack (most recent call first):
  /app/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /app/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/app/build/left -S/app/zmk/app -GNinja -DBOARD=adv360_left -DZMK_CONFIG=/app/config
make: *** [Makefile:15: firmware/$(TIMESTAMP)-left.uf2] Error 1
```

</details>

though it works if I replace `$(PWD)` with `./` there...

```
diff --git a/Makefile b/Makefile
index 35c0006..2f89664 100644
--- a/Makefile
+++ b/Makefile
@@ -11,9 +11,10 @@ clean:
        rm -f firmware/*.uf2

 firmware/%-left.uf2 firmware/%-right.uf2: config/adv360.keymap
-       $(DOCKER) run --rm -it --name zmk \
-               -v $(PWD)/firmware:/app/firmware \
-               -v $(PWD)/config:/app/config:ro \
+       echo $(PWD)
+       $(DOCKER)  run --rm -it --name zmk \
+               -v ./firmware:/app/firmware \
+               -v ./config:/app/config:ro \
                -e TIMESTAMP=$(TIMESTAMP) \
                zmk

```

honestly I'd probably just keep `$(PWD)` in the firmware target, it's less ambiguous than `./`

> Unrelated... 

I think the rest of this feedback is at risk of causing feature creep for a patch that was simply meant to cause make to not fail when rm-ing non-existant files 😄

2022-10-24 20:57 UTC, allanwind commented
Just rename the pull request then.  We are talking about a few lines in the Makefile.  Or if you don't want to do it, say so, and I will submit a PR for it.

2022-10-25 02:57 UTC, craftyguy commented
It's all yours

On October 24, 2022 10:33:45 AM PDT, Allan Wind ***@***.***> wrote:
***@***.*** requested changes on this pull request.
>
>Update commit message to remove the "the single dash" part.  I had a few other suggestions that I suggest we just squeeze in here.
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/KinesisCorporation/Adv360-Pro-ZMK/pull/36#pullrequestreview-1153525480
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

2022-10-25 13:21 UTC, ReFil commented
I'd definitely prefer the other changes being proposed to be in a separate PR

2022-10-25 14:48 UTC, allanwind commented
So let's get those changes in and I will file another PR when this gets merged.

2022-10-30 12:21 UTC, merged